services:
  - type: web
    name: angular-app
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_OPTIONS
        value: --openssl-legacy-provider
      - key: NODE_OPTIONS
        value: --max_old_space_size=1024
